x-api-env: &api-env
  ENVIRONMENT: ${ENVIRONMENT:-dev}
  DB_NAME: ${DB_NAME:-postgres}
  DB_USER: ${DB_USER:-dbuser}
  DB_PASS: ${DB_PASS:-my_db_password}
  DB_HOST: ${DB_HOST:-db}
  DB_PORT: ${DB_PORT:-5432}
  MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
  MINIO_PUBLIC_ENDPOINT: ${MINIO_PUBLIC_ENDPOINT:-http://localhost:9000}
  MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio_admin}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_password}
  MINIO_USE_SSL: ${MINIO_USE_SSL:-false}

services:

  db:
    image: postgis/postgis:18-3.6-alpine
    platform: linux/amd64
    container_name: matchme-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-dbuser}
      POSTGRES_PASSWORD: ${DB_PASS:-my_db_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-dbuser} -d ${DB_NAME:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: matchme_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_password}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API Endpoint
      - "9001:9001" # MinIO Web Console UI (http://localhost:9001)
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matchme-migrator
    command: [ "go", "run", "./cmd/migrator/main.go" ]
    volumes:
      - ./backend:/app
    environment:
      <<: *api-env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matchme-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
    environment:
      <<: *api-env
      JWT_SECRET: ${JWT_SECRET:-super-secure-random-key}
      SERVER_ADDRESS: 0.0.0.0:8080
      SERVER_TIMEOUT: ${SERVER_TIMEOUT:-4s}
      SERVER_IDLE_TIMEOUT: ${SERVER_IDLE_TIMEOUT:-60s}
      SERVER_SHUTDOWN_TIMEOUT: ${SERVER_SHUTDOWN_TIMEOUT:-10s}
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      minio:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matchme-frontend
    ports:
      - "5173:5173"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
